# board alternativos para nRF52840
---
include:
  - board: nrf52840dongle_nrf52840
    shield: ferris_left
    keymap: cardio
  - board: nrf52840dongle_nrf52840
    shield: ferris_right
    keymap: cardio